### ISSUE TITLE
thread 'main' panicked at 'attempt to shift left with overflow'

### ISSUE THREAD

**Issue by james493** [memflow/memflow-pcileech#4]
Hey, I am having some trouble getting the pcileech connector to work when using my Raspberry Pi 4.
Thread panics when calling `Kernel::builder`

<br>

Example code:

```rust
use memflow::connector::*;
use memflow_win32::win32::{Kernel, Keyboard};

use std::{thread, time};

fn main() {
    let inventory = unsafe { ConnectorInventory::scan() };

    let connector = unsafe {
        inventory.create_connector("pcileech", &ConnectorArgs::parse("device=fpga").unwrap())
    }
    .unwrap();

    let mut kernel = Kernel::builder(connector)
        .build_default_caches()
        .build()
        .unwrap();

    let keyboard = Keyboard::try_with(&mut kernel).unwrap();

    loop {
        let keyboard_state = keyboard.state_with_kernel(&mut kernel).unwrap();

        println!("is space down: {:?}", keyboard_state.is_down(0x20));

        thread::sleep(time::Duration::from_secs(1));
    }
}
```

<br>

<details open>
<summary>Full Backtrace</summary>
<br>
<pre>
thread 'main' panicked at 'attempt to shift left with overflow', /home/pi/.cargo/registry/src/github.com-1285ae84e5963aae/memflow-0.1.5/src/architecture/mmu_spec.rs:144:26
stack backtrace:
   0:   0x961220 - std::backtrace_rs::backtrace::libunwind::trace::h8d7576c195706cb5
                       at /rustc/e1884a8e3c3e813aada8254edfa120e85bf5ffca/library/std/src/../../backtrace/src/backtrace/libunwind.rs:100:5
   1:   0x961220 - std::backtrace_rs::backtrace::trace_unsynchronized::hb71812f37eb0ac6c
                       at /rustc/e1884a8e3c3e813aada8254edfa120e85bf5ffca/library/std/src/../../backtrace/src/backtrace/mod.rs:66:5
   2:   0x961220 - std::sys_common::backtrace::_print_fmt::hb367fbcac7015bc2
                       at /rustc/e1884a8e3c3e813aada8254edfa120e85bf5ffca/library/std/src/sys_common/backtrace.rs:67:5
   3:   0x961220 - <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt::h8bfc7af5e604aa9d
                       at /rustc/e1884a8e3c3e813aada8254edfa120e85bf5ffca/library/std/src/sys_common/backtrace.rs:46:22
   4:   0x984284 - core::fmt::write::h12a85d87a0e06c54
                       at /rustc/e1884a8e3c3e813aada8254edfa120e85bf5ffca/library/core/src/fmt/mod.rs:1078:17
   5:   0x95ac04 - std::io::Write::write_fmt::h6c62f0d5091a11ff
                       at /rustc/e1884a8e3c3e813aada8254edfa120e85bf5ffca/library/std/src/io/mod.rs:1518:15
   6:   0x963b90 - std::sys_common::backtrace::_print::h75047bcacb81766e
                       at /rustc/e1884a8e3c3e813aada8254edfa120e85bf5ffca/library/std/src/sys_common/backtrace.rs:49:5
   7:   0x963b90 - std::sys_common::backtrace::print::he3c88810486d29ed
                       at /rustc/e1884a8e3c3e813aada8254edfa120e85bf5ffca/library/std/src/sys_common/backtrace.rs:36:9
   8:   0x963b90 - std::panicking::default_hook::{{closure}}::h4f34c5dfc7a9e970
                       at /rustc/e1884a8e3c3e813aada8254edfa120e85bf5ffca/library/std/src/panicking.rs:208:50
   9:   0x9637ac - std::panicking::default_hook::h3ff73916cce54241
                       at /rustc/e1884a8e3c3e813aada8254edfa120e85bf5ffca/library/std/src/panicking.rs:227:9
  10:   0x9643a4 - std::panicking::rust_panic_with_hook::h3f3bf52125eab9f6
                       at /rustc/e1884a8e3c3e813aada8254edfa120e85bf5ffca/library/std/src/panicking.rs:593:17
  11:   0x963ecc - std::panicking::begin_panic_handler::{{closure}}::hb7e3a9346d657d30
                       at /rustc/e1884a8e3c3e813aada8254edfa120e85bf5ffca/library/std/src/panicking.rs:497:13
  12:   0x96179c - std::sys_common::backtrace::__rust_end_short_backtrace::h8948cf4e4f0d4f4a
                       at /rustc/e1884a8e3c3e813aada8254edfa120e85bf5ffca/library/std/src/sys_common/backtrace.rs:141:18
  13:   0x963e4c - rust_begin_unwind
                       at /rustc/e1884a8e3c3e813aada8254edfa120e85bf5ffca/library/std/src/panicking.rs:495:5
  14:   0x9828e8 - core::panicking::panic_fmt::hd8da8946b8b8cc23
                       at /rustc/e1884a8e3c3e813aada8254edfa120e85bf5ffca/library/core/src/panicking.rs:92:14
  15:   0x982844 - core::panicking::panic::h5b17f6bcdecd0f85
                       at /rustc/e1884a8e3c3e813aada8254edfa120e85bf5ffca/library/core/src/panicking.rs:50:5
  16:   0x4b25cc - memflow::architecture::mmu_spec::ArchMMUSpec::virt_addr_filter::h362c8275ce032de4
                       at /home/pi/.cargo/registry/src/github.com-1285ae84e5963aae/memflow-0.1.5/src/architecture/mmu_spec.rs:144:26
  17:   0x4d729c - <memflow::architecture::x86::X86PageTableBase as memflow::architecture::mmu_spec::MMUTranslationBase>::virt_addr_filter::h0d742dec9a526e6b
                       at /home/pi/.cargo/registry/src/github.com-1285ae84e5963aae/memflow-0.1.5/src/architecture/x86/mod.rs:118:9
  18:   0x4b8ac4 - memflow::architecture::mmu_spec::ArchMMUSpec::virt_to_phys_iter::{{closure}}::hab923d8354a7805f
                       at /home/pi/.cargo/registry/src/github.com-1285ae84e5963aae/memflow-0.1.5/src/architecture/mmu_spec.rs:357:31
  19:   0x4c0954 - core::iter::traits::iterator::Iterator::for_each::call::{{closure}}::h2de99c992cf1f054
                       at /home/pi/.rustup/toolchains/stable-armv7-unknown-linux-gnueabihf/lib/rustlib/src/rust/library/core/src/iter/traits/iterator.rs:675:29
  20:   0x489a80 - core::iter::adapters::map_fold::{{closure}}::hfa2b402199d1bbb8
                       at /home/pi/.rustup/toolchains/stable-armv7-unknown-linux-gnueabihf/lib/rustlib/src/rust/library/core/src/iter/adapters/mod.rs:905:21
  21:   0x502418 - core::iter::traits::iterator::Iterator::fold::hed8a426a7bdd9093
                       at /home/pi/.rustup/toolchains/stable-armv7-unknown-linux-gnueabihf/lib/rustlib/src/rust/library/core/src/iter/traits/iterator.rs:2023:21
  22:   0x48aa60 - <core::iter::adapters::Map<I,F> as core::iter::traits::iterator::Iterator>::fold::h86b50c50866a677a
                       at /home/pi/.rustup/toolchains/stable-armv7-unknown-linux-gnueabihf/lib/rustlib/src/rust/library/core/src/iter/adapters/mod.rs:945:9
  23:   0x484b10 - core::iter::traits::iterator::Iterator::for_each::h89c4dc6fbcf8a861
                       at /home/pi/.rustup/toolchains/stable-armv7-unknown-linux-gnueabihf/lib/rustlib/src/rust/library/core/src/iter/traits/iterator.rs:678:9
  24:   0x4b6e14 - memflow::architecture::mmu_spec::ArchMMUSpec::virt_to_phys_iter::he75fd1af6b525456
                       at /home/pi/.cargo/registry/src/github.com-1285ae84e5963aae/memflow-0.1.5/src/architecture/mmu_spec.rs:357:9
  25:   0x4d78b4 - <memflow::architecture::x86::X86ScopedVirtualTranslate as memflow::architecture::ScopedVirtualTranslate>::virt_to_phys_iter::hc47e17cfb28d5cff
                       at /home/pi/.cargo/registry/src/github.com-1285ae84e5963aae/memflow-0.1.5/src/architecture/x86/mod.rs:77:9
  26:   0x4f091c - <memflow_win32::win32::vat::Win32VirtualTranslate as memflow::architecture::ScopedVirtualTranslate>::virt_to_phys_iter::h37e8e463fa5f942d
                       at /home/pi/.cargo/registry/src/github.com-1285ae84e5963aae/memflow-win32-0.1.5/src/win32/vat.rs:46:9
  27:   0x4d8d90 - <memflow::mem::virt_translate::direct_translate::DirectTranslate as memflow::mem::virt_translate::VirtualTranslate>::virt_to_phys_iter::ha22870484b84074e
                       at /home/pi/.cargo/registry/src/github.com-1285ae84e5963aae/memflow-0.1.5/src/mem/virt_translate/direct_translate.rs:48:9
  28:   0x48e85c - <memflow::mem::virt_mem::virtual_dma::VirtualDMA<T,V,D> as memflow::mem::virt_mem::VirtualMemory>::virt_read_raw_list::h9b7e0fe0b51b94af
                       at /home/pi/.cargo/registry/src/github.com-1285ae84e5963aae/memflow-0.1.5/src/mem/virt_mem/virtual_dma.rs:167:9
  29:   0x4907e4 - memflow::mem::virt_mem::VirtualMemory::virt_read_raw_into::hb65c9e629f60f54e
                       at /home/pi/.cargo/registry/src/github.com-1285ae84e5963aae/memflow-0.1.5/src/mem/virt_mem.rs:68:9
  30:   0x4f6598 - memflow_win32::kernel::ntos::x64::find_with_va::h1ab6bae40c2898e1
                       at /home/pi/.cargo/registry/src/github.com-1285ae84e5963aae/memflow-win32-0.1.5/src/kernel/ntos/x64.rs:51:5
  31:   0x4f72b4 - memflow_win32::kernel::ntos::x64::find_with_va_hint::h3b0da2ff0bc2fcb0
                       at /home/pi/.cargo/registry/src/github.com-1285ae84e5963aae/memflow-win32-0.1.5/src/kernel/ntos/x64.rs:32:15
  32:   0x49ba34 - memflow_win32::kernel::ntos::find::hcb48f0f7b69297a4
                       at /home/pi/.cargo/registry/src/github.com-1285ae84e5963aae/memflow-win32-0.1.5/src/kernel/ntos.rs:25:19
  33:   0x4f7f40 - memflow_win32::win32::kernel_info::KernelInfoScanner<T>::scan_block::h019c14b9ba61d026
                       at /home/pi/.cargo/registry/src/github.com-1285ae84e5963aae/memflow-win32-0.1.5/src/win32/kernel_info.rs:90:42
  34:   0x4f8efc - memflow_win32::win32::kernel_info::KernelInfoScanner<T>::scan::hbb89245cd3c531a9
                       at /home/pi/.cargo/registry/src/github.com-1285ae84e5963aae/memflow-win32-0.1.5/src/win32/kernel_info.rs:69:9
  35:   0x4e48d8 - memflow_win32::win32::kernel_builder::KernelBuilder<T,TK,VK>::build::hbe810d6b7d5e76d3
                       at /home/pi/.cargo/registry/src/github.com-1285ae84e5963aae/memflow-win32-0.1.5/src/win32/kernel_builder.rs:165:27
  36:   0x4d6e64 - memflow_example::main::hf441285be6c658fe
                       at /home/pi/Desktop/memflow-example/src/main.rs:14:22
  37:   0x49cff8 - core::ops::function::FnOnce::call_once::h4ab1114182d422f1
                       at /home/pi/.rustup/toolchains/stable-armv7-unknown-linux-gnueabihf/lib/rustlib/src/rust/library/core/src/ops/function.rs:227:5
  38:   0x4bcef0 - std::sys_common::backtrace::__rust_begin_short_backtrace::h2472f19baac95026
                       at /home/pi/.rustup/toolchains/stable-armv7-unknown-linux-gnueabihf/lib/rustlib/src/rust/library/std/src/sys_common/backtrace.rs:125:18
  39:   0x4bf0b8 - std::rt::lang_start::{{closure}}::h7d49f484dc63886d
                       at /home/pi/.rustup/toolchains/stable-armv7-unknown-linux-gnueabihf/lib/rustlib/src/rust/library/std/src/rt.rs:66:18
  40:   0x9647b0 - core::ops::function::impls::<impl core::ops::function::FnOnce<A> for &F>::call_once::h8808c2ef4f70f9f6
                       at /rustc/e1884a8e3c3e813aada8254edfa120e85bf5ffca/library/core/src/ops/function.rs:259:13
  41:   0x9647b0 - std::panicking::try::do_call::h6a1485bf7d01fff1
                       at /rustc/e1884a8e3c3e813aada8254edfa120e85bf5ffca/library/std/src/panicking.rs:381:40
  42:   0x9647b0 - std::panicking::try::hff4de2efce65f689
                       at /rustc/e1884a8e3c3e813aada8254edfa120e85bf5ffca/library/std/src/panicking.rs:345:19
  43:   0x9647b0 - std::panic::catch_unwind::hf743cc466168988c
                       at /rustc/e1884a8e3c3e813aada8254edfa120e85bf5ffca/library/std/src/panic.rs:396:14
  44:   0x9647b0 - std::rt::lang_start_internal::h80f7e1a94a5fb8b5
                       at /rustc/e1884a8e3c3e813aada8254edfa120e85bf5ffca/library/std/src/rt.rs:51:25
  45:   0x4bf08c - std::rt::lang_start::haa990e2114f062ca
                       at /home/pi/.rustup/toolchains/stable-armv7-unknown-linux-gnueabihf/lib/rustlib/src/rust/library/std/src/rt.rs:65:5
  46:   0x4d708c - main
  47: 0xb6cba718 - __libc_start_main
</pre>
</details>

**Comment by h33p** [comment]
I've narrowed down the issue. If I am not mistaken, you are running a 32-bit OS on the Pi (or compiled your code as 32-bit). Unfortunately, Using 32-bit code to analyze 64-bit OSes is not supported, until memflow 0.2.

To use with pcileech, it will be necessary to install 64-bit image of Raspberry Pi OS (or any other distribution), and use 64-bit rust compiler (which I believe should be the default if OS is 64-bit)

**Comment by ko1N** [comment]
Right, this is a feature we have planned for a later stage (analyzing 64bit targets from 32bit guests).

For future reference here is the link to the 64-bit beta version of Raspbian which I'm also currently using with memflow:
https://www.raspberrypi.org/forums/viewtopic.php?t=275370 (the last post)

**Comment by james493** [comment]
Thank you! It works now :smiley:
