### ISSUE TITLE
Reduce output?

### ISSUE THREAD

**Issue by windows-fryer** [memflow/memflow-pcileech#9]
After starting the connector I get a lot of output from something down the pipeline (I believe pcileech). Is there any way to remove this output via the flags I can pass?

![image](https://github.com/memflow/memflow-pcileech/assets/90010895/2d59153c-2e01-4e38-98a8-2e084e3c02c8)

**Comment by ko1N** [comment]
Hey there, welcome and thanks for your issue. I think this could be a great suggestion. I can see 2 potential ways of achieving this currently. The  LC_CONFIG contains 2 fields reponsible for log output:

```
    DWORD dwPrintfVerbosity;                // printf verbosity according to LC_PRINTF_*
    _Check_return_opt_ int(*pfn_printf_opt)(_In_z_ _Printf_format_string_ char const *const _Format, ...);
```

Maybe it would be good to set the verbosity according to the current log setting the user has configured. Additionally it would be nice to overwrite the printf method and forward it to the rust logging facade as well.

Currently there is no way however to have extern C funcs that are variadic in Rust (See https://github.com/rust-lang/rust/issues/44930). However maybe a small C wrapper could be made that achieves this?

**Comment by ko1N** [comment]
Can you try the new version i just pushed? This should take into account the current rust logging level witha dwPrintfVerbosity now.

**Comment by windows-fryer** [comment]
Looks like this has solved the issue I was having, thanks a lot!
